name: cache pip downloads

on: push

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: caching the files
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip 
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: python3 -m pip install --user -r requirements.txt
