name: A workflow with real steps 

on: 
 push:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: get checkout
        uses: actions/checkout@v4

      - name: kernal details
        run: uname -s

      - name: lsit the repo
        working-directory: actions-journey
        run: ls 
