name: fan-out fan-in workflow

on: push 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hellow"
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "world class" 
  package: 
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    steps:
      - run: echo  "after the lint and unit-test"


