name: upload a build report

on: push

jobs:
  report-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: generate report
        run: echo "$date" > report.txt
      - name: upload the report
        uses: actions/upload-artifact@v4
        with: 
          name: build-report
          path: report.txt
          retention-days: 5

